# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 593d045fbee14359575e8dd1890bf5c0bdf5b8a7791fb3df882b833d350fdc9505620c1b57b33d38a9c311285a74756d9c9acb4edc8e34ce1db6c6e8b51a226c

test:
  secret_key_base: 5c5316c98a75bc250ca6d3b8adf715f966a9ce27ee9532d73ab5bd4077e0976caac4a1ca80c2cfd4758942bd35538efa253de187de656b768674fbdaed791445

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
